name: Push changes to nsaph-platform-docs
on:
  push:
    branches:
      - feature/automatic_documentation

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest -v

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow and Wait
        uses: convictional/trigger-workflow-and-wait@v1.6.3
        with:
          owner: quantori
          ref: feature/automatic_documentation
          repo: nsaph-platform-docs
          github_token: ${{ secrets.ACCESS_TOKEN }}
          workflow_file_name: deploy.yml
